config/routes.rb
Rails.application.routes.draw do
  resources :line_items
  get 'orders/emailit'

  resources :orders do
    resources :email_recipients
  end
  root to: 'orders#index'

  resources :posts do
    resources :comments
  end
  devise_for :users, controllers: { registration: "registrations" }

end

app/models/email_recipient.rb
class EmailRecipient < ActiveRecord::Base
  belongs_to :order
  belongs_to :user
end

app/controllers/email_recipients_controller.rb
class EmailRecipientsController < ApplicationController
  before_action :set_email_recipient, only: [:show, :edit, :update, :destroy]

  # GET /email_recipients
  # GET /email_recipients.json
  def index
    @email_recipients = EmailRecipient.all
  end

  # GET /email_recipients/1
  # GET /email_recipients/1.json
  def show
  end

  # GET /email_recipients/new
  def new
    @email_recipient = EmailRecipient.new
  end

  # GET /email_recipients/1/edit
  def edit
  end

  # POST /email_recipients
  # POST /email_recipients.json
  def create
    @order = Order.find(params[:order_id]) # how to use current object?
    @email_recipient = EmailRecipient.new(email_recipient_params)
    @user = current_user

    respond_to do |format|
      if @email_recipient.save
        pdf = OrderPdf.new(@order, view_context) # initialize the OrderPdf class # pass an argument as this is required in the class that you've made
        pdf.render_file File.join(Rails.root, "tmp", "x.pdf")
        current_user.certificate = File.open("#{Rails.root}/tmp/x.pdf")
        current_user.save!
        PdfMailer.email_pdf(@email_recipient, @user).deliver

        format.html { redirect_to order_email_recipient_path(@order, @email_recipient), notice: "Successfully sent" }
        format.json { render :show, status: :created, location: @email_recipient }
      else
        format.html { render :new }
        format.json { render json: @email_recipient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /email_recipients/1
  # PATCH/PUT /email_recipients/1.json
  def update
    respond_to do |format|
      if @email_recipient.update(email_recipient_params)
        format.html { redirect_to order_email_recipient_path(@order, @email_recipient), notice: 'Email recipient was successfully updated.' }
        format.json { render :show, status: :ok, location: @email_recipient }
      else
        format.html { render :edit }
        format.json { render json: @email_recipient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /email_recipients/1
  # DELETE /email_recipients/1.json
  def destroy
    @email_recipient.destroy
    respond_to do |format|
      format.html { redirect_to email_recipients_url, notice: 'Email recipient was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_email_recipient
      @email_recipient = EmailRecipient.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def email_recipient_params
      params.require(:email_recipient).permit(:email, :subject, :content, :user_id)
    end
end

app/helpers/email_recipients_helper.rb
module EmailRecipientsHelper
end

app/views/email_recipients/_form.html.erb
<%= form_for([:order, @email_recipient]) do |f| %>

  <% if @email_recipient.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@email_recipient.errors.count, "error") %> prohibited this email_recipient from being saved:</h2>

      <ul>
      <% @email_recipient.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email_recipient %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :subject %><br>
    <%= f.text_field :subject %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <p> Note: The PDF's already attached </p>
  <div class="actions">
    <%= f.submit "Send PDF Receipt" %>
  </div>
<% end %>

app/views/email_recipients/edit.html.erb
<h1>Editing Email Recipient</h1>

<%= render 'form' %>

<%= link_to 'Show', @email_recipient %> |
<%= link_to 'Back', email_recipients_path %>

app/views/email_recipients/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Email Recipients</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th>Subject</th>
      <th>Content</th>
      <th>Order</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @email_recipients.each do |email_recipient| %>
      <tr>
        <td><%= email_recipient.email %></td>
        <td><%= email_recipient.subject %></td>
        <td><%= email_recipient.content %></td>
        <td><%= email_recipient.order_id %></td>
        <td><%= link_to 'Show', email_recipient %></td>
        <td><%= link_to 'Edit', edit_email_recipient_path(email_recipient) %></td>
        <td><%= link_to 'Destroy', email_recipient, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Email recipient', new_email_recipient_path %>

app/views/email_recipients/new.html.erb
<h1>Compose Email:</h1>

<%= render 'form' %>

<%= link_to 'Back', email_recipients_path %>

app/views/email_recipients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Sent To:</strong>
  <%= @email_recipient.email %>
</p>

<p>
  <strong>Subject:</strong>
  <%= @email_recipient.subject %>
</p>

<p>
  <strong>Content:</strong>
  <%= @email_recipient.content %>
</p>


<%= link_to 'Go Back to Orders', orders_path %> |