config/routes.rb
Rails.application.routes.draw do
  resources :line_items
  get 'orders/emailit'

  resources :orders do
    resources :email_recipients
  end
  root to: 'orders#index'

  resources :posts do
    resources :comments
  end
  devise_for :users, controllers: { registration: "registrations" }

end

app/models/order.rb
class Order < ActiveRecord::Base
  has_many :line_items
  has_many :email_recipients
  belongs_to :user

  def total_price
    # convert to array so it doesn't try to do sum on database directly
    line_items.to_a.sum(&:full_price)
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def index
    @orders = Order.all
  end

  def show
    @order = Order.find(params[:id])
    respond_to do |format|
      format.html
      format.pdf do # send back the data for teh pdf docment
        pdf = OrderPdf.new(@order, view_context) # initialize the OrderPdf class # pass an argument as this is required in the class that you've made
        send_data pdf.render, filename: "order_#{@order.order_number}.pdf", # pass the filename argument as well to indicate the filename
                              type: "application/pdf", # set this, otherwise it deafults to an application/octet-stream (it means that it's a binary file that needs to be opened in some application, such as a spreadsheet or word processor)
                              disposition: "inline" # just do it inline without downloading it
      pdf.render_file File.join(Rails.root, "tmp", "x.pdf")
      current_user.certificate = File.open("#{Rails.root}/tmp/x.pdf")
      current_user.save!

      end
    end
  end

  def emailit

  end

  def new
    @order = Order.new

  end


  def create


  end


  private

  def email_recipient_params
    params.require(:email_recipient).permit(:email, :subject, :content, :user_id)
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_form.html.erb
<%= form_for(@order) do |f| %>
  <% if @order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% @order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :order_number %><br>
    <%= f.text_field :order_number %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/orders/edit.html.erb
<h1>Editing Order</h1>

<%= render 'form' %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/emailit.html.erb
<h1>Orders#emailit</h1>
<p>Find me in app/views/orders/emailit.html.erb</p>

<% form_for @order.email_recipient do |o| %>
    <div class="field">
    <%= f.label :email_recipient %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :subject %><br>
    <%= f.text_field :subject %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <p> Note: The PDF's already attached </p>
  <div class="actions">
    <%= f.submit "Send PDF Receipt" %>
  </div>

<% end %>

app/views/orders/index.html.erb
<h1>Orders</h1>
<ul>
<% @orders.each do |order| %>
  <li><%= link_to "Order \##{order.order_number}", order %></li>
<% end %>
</ul>

app/views/orders/new.html.erb
<h1>New Order</h1>

<%= render 'form' %>

<%= link_to 'Back', orders_path %>

app/views/orders/show.html.erb
<h1>Order #<%= @order.order_number %></h1>

<table id="line_items", class="table table-bordered">
  <tr>
    <th>Product</th>
    <th>Qty</th>
    <th class="price">Unit Price</th>
    <th class="price">Full Price</th>
  </tr>
  <% @order.line_items.each do |line_item| %>
    <tr class="<%= cycle :odd, :even %>">
      <td><%= line_item.name %></td>
      <td class="qty"><%= line_item.quantity %></td>
      <td class="price"><%= number_to_currency(line_item.unit_price) %></td>
      <td class="price"><%= number_to_currency(line_item.full_price) %></td>
    </tr>
  <% end %>
  <tr>
    <td class="total price" colspan="4">
      Total: <%= number_to_currency @order.total_price %>
    </td>
  </tr>
</table>

<p><%= link_to "Print Receipt (PDF)", order_path(@order, format: "pdf"), class: "btn btn-default" %> </p>
<p><%= link_to "Email Receipt (PDF)", new_order_email_recipient_path(order_id: @order.id), class: "btn btn-default" %> </p>
<p><%= link_to "Go Back to Orders", orders_path %> </p>